# Generated by Django 5.0.6 on 2024-05-20 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe1', '0002_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
